// operational-portal/src/app/login.tsx
import React, { useState, useEffect } from 'react';

interface LoginFormData {
  email: string;
  password: string;
}

interface FormErrors {
  email: string[];
  password: string[];
}

interface LoginResponse {
  success: boolean;
  message: string;
  data: {
    user: {
      id: number;
      name: string;
      email: string;
      status: string;
      role_id: number;
      created_at: string;
    };
    accessToken: string;
    refreshToken: string;
  };
}

const LoginComponent: React.FC = () => {
  const [formData, setFormData] = useState<LoginFormData>({
    email: '',
    password: ''
  });
  const [errors, setErrors] = useState<FormErrors>({
    email: [],
    password: []
  });
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  useEffect(() => {
    // Check if user is already logged in
    const accessToken = localStorage.getItem('accessToken');
    if (accessToken) {
      console.log('User is already authenticated');
    }
  }, []);

  const validateEmail = (email: string): string[] => {
    const errors: string[] = [];
    if (!email) {
      errors.push('Email is required');
    } else {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        errors.push('Please enter a valid email address');
      }
    }
    return errors;
  };

  const validatePassword = (password: string): string[] => {
    const errors: string[] = [];
    if (!password) {
      errors.push('Password is required');
    } else if (password.length < 6) {
      errors.push('Password must be at least 6 characters long');
    }
    return errors;
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));

    // Clear errors when user starts typing
    if (errors[name as keyof FormErrors].length > 0) {
      setErrors(prev => ({
        ...prev,
        [name]: []
      }));
    }
  };

  const validateForm = (): boolean => {
    const emailErrors = validateEmail(formData.email);
    const passwordErrors = validatePassword(formData.password);
    
    const newErrors: FormErrors = {
      email: emailErrors,
      password: passwordErrors
    };
    
    setErrors(newErrors);
    return emailErrors.length === 0 && passwordErrors.length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    setIsLoading(true);
    setErrorMessage('');
    setSuccessMessage('');

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Login failed');
      }

      const data: LoginResponse = await response.json();
      
      // Store tokens in localStorage
      localStorage.setItem('accessToken', data.data.accessToken);
      localStorage.setItem('refreshToken', data.data.refreshToken);
      localStorage.setItem('user', JSON.stringify(data.data.user));

      setSuccessMessage('Login successful! Redirecting...');
      
      // Redirect to dashboard after successful login
      setTimeout(() => {
        console.log('Login successful:', data);
      }, 1000);
      
    } catch (error: any) {
      setErrorMessage(error.message || 'Login failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const isFieldInvalid = (fieldName: keyof FormErrors): boolean => {
    return errors[fieldName].length > 0;
  };

  return (
    <div className="shared-login-container">
      <div className="shared-login-card">
        <div className="shared-login-header">
          <h1 className="shared-login-title">Welcome Back</h1>
          <p className="shared-login-subtitle">Sign in to your account to continue</p>
        </div>

        {/* Success Message */}
        {successMessage && (
          <div className="shared-alert success">
            {successMessage}
          </div>
        )}

        {/* Error Message */}
        {errorMessage && (
          <div className="shared-alert error">
            {errorMessage}
          </div>
        )}

        <form onSubmit={handleSubmit}>
          {/* Email Field */}
          <div className="shared-form-group">
            <label htmlFor="email" className="shared-form-label">
              Email Address
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleInputChange}
              className={`shared-form-input ${isFieldInvalid('email') ? 'error' : ''}`}
              placeholder="Enter your email"
              autoComplete="email"
            />
            {isFieldInvalid('email') && (
              <span className="shared-form-error">
                {errors.email[0]}
              </span>
            )}
          </div>

          {/* Password Field */}
          <div className="shared-form-group">
            <label htmlFor="password" className="shared-form-label">
              Password
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleInputChange}
              className={`shared-form-input ${isFieldInvalid('password') ? 'error' : ''}`}
              placeholder="Enter your password"
              autoComplete="current-password"
            />
            {isFieldInvalid('password') && (
              <span className="shared-form-error">
                {errors.password[0]}
              </span>
            )}
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            className="shared-form-button"
            disabled={isLoading}
          >
            {isLoading && <span className="shared-loading"></span>}
            {isLoading ? 'Signing In...' : 'Sign In'}
          </button>
        </form>

        {/* Toggle to Signup */}
        <div className="shared-form-toggle">
          Don't have an account?
          <a href="/signup" className="shared-form-toggle-link">
            Sign up here
          </a>
        </div>
      </div>
    </div>
  );
};

export default LoginComponent;

// admin-portal/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';

interface LoginCredentials {
  email: string;
  password: string;
}

interface LoginResponse {
  success: boolean;
  message: string;
  data: {
    user: {
      id: number;
      name: string;
      email: string;
      status: string;
      role_id: number;
      created_at: string;
    };
    accessToken: string;
    refreshToken: string;
  };
}

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule, 
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatSelectModule
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  isLoading = false;
  errorMessage = '';
  successMessage = '';
  hidePassword = true;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private http: HttpClient,
    private snackBar: MatSnackBar
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  ngOnInit(): void {
    // Check if user is already logged in
    const accessToken = localStorage.getItem('admin_accessToken');
    if (accessToken) {
      this.router.navigate(['/admin/dashboard']);
    }
  }

  async onSubmit(): Promise<void> {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';
      this.successMessage = '';

      const credentials: LoginCredentials = {
        email: this.loginForm.value.email,
        password: this.loginForm.value.password
      };

      try {
        const response = await this.http.post<LoginResponse>('/api/auth/login', credentials).toPromise();
        
        if (response) {
          // Store tokens in localStorage with admin prefix
          localStorage.setItem('admin_accessToken', response.data.accessToken);
          localStorage.setItem('admin_refreshToken', response.data.refreshToken);
          localStorage.setItem('admin_user', JSON.stringify(response.data.user));

          this.successMessage = 'Login successful! Redirecting to admin dashboard...';
          this.snackBar.open('Login successful!', 'Close', {
            duration: 3000,
            horizontalPosition: 'center',
            verticalPosition: 'top',
          });
          
          setTimeout(() => {
            this.router.navigate(['/admin/dashboard']);
          }, 1000);
        }
      } catch (error: any) {
        this.errorMessage = error.error?.message || 'Login failed. Please try again.';
        this.snackBar.open(this.errorMessage, 'Close', {
          duration: 5000,
          horizontalPosition: 'center',
          verticalPosition: 'top',
          panelClass: ['error-snackbar']
        });
      } finally {
        this.isLoading = false;
      }
    } else {
      this.markFormGroupTouched();
    }
  }

  private markFormGroupTouched(): void {
    Object.keys(this.loginForm.controls).forEach(key => {
      const control = this.loginForm.get(key);
      control?.markAsTouched();
    });
  }

  getErrorMessage(fieldName: string): string {
    const field = this.loginForm.get(fieldName);
    if (field?.errors && field.touched) {
      if (field.errors['required']) {
        return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} is required`;
      }
      if (field.errors['email']) {
        return 'Please enter a valid email address';
      }
      if (field.errors['minlength']) {
        return `Password must be at least ${field.errors['minlength'].requiredLength} characters`;
      }
    }
    return '';
  }

  isFieldInvalid(fieldName: string): boolean {
    const field = this.loginForm.get(fieldName);
    return !!(field?.invalid && field?.touched);
  }

  togglePasswordVisibility(): void {
    this.hidePassword = !this.hidePassword;
  }
}



<!-- Top Navbar -->
<div class="flex items-center p-4 shadow-sm">
  <mat-icon>flag</mat-icon>
  <h1 class="ml-2 font-bold text-lg">TechQnA</h1>
</div>

<!-- Centered Form Container -->
<div class="flex items-center justify-center min-h-[80vh] bg-white">
  <div class="w-full max-w-md px-6 py-8">
    <h2 class="text-center text-2xl font-bold mb-6">Login</h2>

    <form>
      <mat-form-field appearance="outline" class="w-full mb-4">
        <mat-label>Email</mat-label>
        <input matInput placeholder="Email" type="email">
      </mat-form-field>

      <mat-form-field appearance="outline" class="w-full mb-6">
        <mat-label>Password</mat-label>
        <input matInput placeholder="Password" type="password">
      </mat-form-field>

      <button mat-raised-button color="primary"
              class="w-full bg-black hover:bg-gray-900 text-white py-2 rounded-full mb-4">
        Login
      </button>

      <div class="text-center text-sm text-gray-500 mb-4">or</div>

      <button mat-stroked-button class="w-full rounded-full bg-gray-100 font-semibold">
        Login with Google
      </button>
    </form>
  </div>
</div>
